[package]
name = "jira-pr-status-updater"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/pr-status-updater.rs"
crate-type = ["cdylib"]

[dependencies]
regex = "1.6.0"
flows-connector-dsi = { git="https://github.com/flows-network/flows-connector-dsi" }
wasmedge-bindgen = "0.4.0"
wasmedge-bindgen-macro = "0.4.0"
