[package]
name = "sync-pr-to-jira"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/sync-pr-to-jira.rs"
crate-type = ["cdylib"]

[dependencies]
flows-connector-dsi = { git="https://github.com/flows-network/flows-connector-dsi" }
wasmedge-bindgen = "0.4.0"
wasmedge-bindgen-macro = "0.4.0"
